CREATE TABLE IF NOT EXISTS conversion_factor (
    id BIGSERIAL PRIMARY KEY,
    u_entrada VARCHAR(50) NOT NULL,
    u_salida VARCHAR(50) NOT NULL,
    factor DOUBLE PRECISION NOT NULL
);

ALTER TABLE conversion_factor ADD COLUMN IF NOT EXISTS magnitud VARCHAR(50);